# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03daa258da99448b877b971c16470dcd9e89239e58ad356384245bbea9feaa16d851cac6718168dcc1fccda545987cdcf631526989f3a4eb70dea6d9fb5cfc6c

test:
  secret_key_base: be590ff61990a66a4ce11dd95f70c2d4b702b3942b686f013341422e590c02d03ff447ef3fa488d6353cad68cb4661ff7f804eb5744ff24d2759dd90f85469c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
